baseURL = "https://pilomyblog.netlify.app/"
languageCode = "en-us"
title = "Pilo"
theme = "PaperMod"

[params]
  author = "Mark Ople"
  ShowDate = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true
