baseURL = "https://your-netlify-site-name.netlify.app/"
languageCode = 'en-us'
title = "Pilo"
theme = "PaperMod"

# Optional PaperMod parameters
[params]
  author = "Mark Ople"
  # ShowReadingTime = true
  ShowDate = true
  mainSections = ["posts"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true