baseURL = "https://pilomyblog.netlify.app/"
languageCode = "en-us"
title = "Pilo"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  author = "Mark Ople"
  ShowDate = true
  # Add these lines:
  showPostMeta = true
  # ShowReadingTime = true
  ShowBreadCrumbs = true
  hideMeta = false

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 2

  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[markup]
  [markup.goldmark.renderer]
    unsafe = true
